# Kepler Dataset

Essential Imports

In [ ]:
import pandas as pd

Reading the CSV

In [ ]:
df = pd.read_csv('/content/exoplanetdata.csv')

In [ ]:
df.head()

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0.0,0.0,0.0,0.0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0.0,0.0,0.0,0.0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0.0,0.0,0.0,0.0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0.0,1.0,0.0,0.0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0.0,0.0,0.0,0.0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

We have 9563 rows of data with 49 possible features.

In [ ]:
df.shape

(6314, 49)

In [ ]:
df.columns

Index(['kepid', 'kepoi_name', 'kepler_name', 'koi_disposition',
       'koi_pdisposition', 'koi_score', 'koi_fpflag_nt', 'koi_fpflag_ss',
       'koi_fpflag_co', 'koi_fpflag_ec', 'koi_period', 'koi_period_err1',
       'koi_period_err2', 'koi_time0bk', 'koi_time0bk_err1',
       'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1', 'koi_impact_err2',
       'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth',
       'koi_depth_err1', 'koi_depth_err2', 'koi_prad', 'koi_prad_err1',
       'koi_prad_err2', 'koi_teq', 'koi_teq_err1', 'koi_teq_err2', 'koi_insol',
       'koi_insol_err1', 'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num',
       'koi_tce_delivname', 'koi_steff', 'koi_steff_err1', 'koi_steff_err2',
       'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad',
       'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec', 'koi_kepmag'],
      dtype='object')

In [ ]:
df.head(10)

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0.0,0.0,0.0,0.0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0.0,0.0,0.0,0.0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0.0,0.0,0.0,0.0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0.0,1.0,0.0,0.0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0.0,0.0,0.0,0.0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
5,10872983,K00756.01,Kepler-228 d,CONFIRMED,CANDIDATE,1.000,0.0,0.0,0.0,0.0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714
6,10872983,K00756.02,Kepler-228 c,CONFIRMED,CANDIDATE,1.000,0.0,0.0,0.0,0.0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714
7,10872983,K00756.03,Kepler-228 b,CONFIRMED,CANDIDATE,0.992,0.0,0.0,0.0,0.0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714
8,6721123,K00114.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0.0,1.0,1.0,0.0,...,-124.0,3.986,0.182,-0.098,1.958,0.322,-0.483,298.86435,42.151569,12.660
9,10910878,K00757.01,Kepler-229 c,CONFIRMED,CANDIDATE,1.000,0.0,0.0,0.0,0.0,...,-83.0,4.485,0.083,-0.028,0.848,0.033,-0.072,286.99948,48.375790,15.841

We look for the null values of the dataset.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6314 entries, 0 to 6313
Data columns (total 49 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   kepid              6314 non-null   int64
 1   kepoi_name         6314 non-null   object
 2   kepler_name        2693 non-null   object
 3   koi_disposition    6313 non-null   object
 4   koi_pdisposition   6313 non-null   object
 5   koi_score          5786 non-null   float64
 6   koi_fpflag_nt      6313 non-null   float64
 7   koi_fpflag_ss      6313 non-null   float64
 8   koi_fpflag_co      6313 non-null   float64
 9   koi_fpflag_ec      6313 non-null   float64
 10  koi_period         6313 non-null   float64
 11  koi_period_err1    6146 non-null   float64
 12  koi_period_err2    6146 non-null   float64
 13  koi_time0bk        6313 non-null   float64
 14  koi_time0bk_err1   6146 non-null   float64
 15  koi_time0bk_err2   6146 non-null   float64
 16  koi_impact         6184 non-null   float64
 17  koi_impact_err1    6146 non-null   float64
 18  koi_impact_err2    6146 non-null   float64
 19  koi_duration       6313 non-null   float64
 20  koi_duration_err1  6146 non-null   float64
 21  koi_duration_err2  6146 non-null   float64
 22  koi_depth          6184 non-null   float64
 23  koi_depth_err1     6146 non-null   float64
 24  koi_depth_err2     6146 non-null   float64
 25  koi_prad           6184 non-null   float64
 26  koi_prad_err1      6184 non-null   float64
 27  koi_prad_err2      6184 non-null   float64
 28  koi_teq            6184 non-null   float64
 29  koi_teq_err1       0 non-null      float64
 30  koi_teq_err2       0 non-null      float64
 31  koi_insol          6193 non-null   float64
 32  koi_insol_err1     6193 non-null   float64
 33  koi_insol_err2     6193 non-null   float64
 34  koi_model_snr      6184 non-null   float64
 35  koi_tce_plnt_num   5988 non-null   float64
 36  koi_tce_delivname  5988 non-null   object
 37  koi_steff          6184 non-null   float64
 38  koi_steff_err1     6106 non-null   float64
 39  koi_steff_err2     6092 non-null   float64
 40  koi_slogg          6184 non-null   float64
 41  koi_slogg_err1     6106 non-null   float64
 42  koi_slogg_err2     6106 non-null   float64
 43  koi_srad           6184 non-null   float64
 44  koi_srad_err1      6106 non-null   float64
 45  koi_srad_err2      6106 non-null   float64
 46  ra                 6313 non-null   float64
 47  dec                6313 non-null   float64
 48  koi_kepmag         6313 non-null   float64
dtypes: float64(43), int64(1), object(5)
memory usage: 2.4+ MB

In [ ]:
df.dtypes

kepid                  int64
kepoi_name            object
kepler_name           object
koi_disposition       object
koi_pdisposition      object
koi_score            float64
koi_fpflag_nt        float64
koi_fpflag_ss        float64
koi_fpflag_co        float64
koi_fpflag_ec        float64
koi_period           float64
koi_period_err1      float64
koi_period_err2      float64
koi_time0bk          float64
koi_time0bk_err1     float64
koi_time0bk_err2     float64
koi_impact           float64
koi_impact_err1      float64
koi_impact_err2      float64
koi_duration         float64
koi_duration_err1    float64
koi_duration_err2    float64
koi_depth            float64
koi_depth_err1       float64
koi_depth_err2       float64
koi_prad             float64
koi_prad_err1        float64
koi_prad_err2        float64
koi_teq              float64
koi_teq_err1         float64
koi_teq_err2         float64
koi_insol            float64
koi_insol_err1       float64
koi_insol_err2       float64
koi_model_snr        float64
koi_tce_plnt_num     float64
koi_tce_delivname     object
koi_steff            float64
koi_steff_err1       float64
koi_steff_err2       float64
koi_slogg            float64
koi_slogg_err1       float64
koi_slogg_err2       float64
koi_srad             float64
koi_srad_err1        float64
koi_srad_err2        float64
ra                   float64
dec                  float64
koi_kepmag           float64
dtype: object

We notice that kepler name has a lot of empty values, but it is due to the status of the exoplanet classification. But other than that, the null values need to be dealt with so that we can have a cleaned dataset.

In [ ]:
df.isnull().sum()

kepid                   0
kepoi_name              0
kepler_name          3621
koi_disposition         1
koi_pdisposition        1
koi_score             528
koi_fpflag_nt           1
koi_fpflag_ss           1
koi_fpflag_co           1
koi_fpflag_ec           1
koi_period              1
koi_period_err1       168
koi_period_err2       168
koi_time0bk             1
koi_time0bk_err1      168
koi_time0bk_err2      168
koi_impact            130
koi_impact_err1       168
koi_impact_err2       168
koi_duration            1
koi_duration_err1     168
koi_duration_err2     168
koi_depth             130
koi_depth_err1        168
koi_depth_err2        168
koi_prad              130
koi_prad_err1         130
koi_prad_err2         130
koi_teq               130
koi_teq_err1         6314
koi_teq_err2         6314
koi_insol             121
koi_insol_err1        121
koi_insol_err2        121
koi_model_snr         130
koi_tce_plnt_num      326
koi_tce_delivname     326
koi_steff             130
koi_steff_err1        208
koi_steff_err2        222
koi_slogg             130
koi_slogg_err1        208
koi_slogg_err2        208
koi_srad              130
koi_srad_err1         208
koi_srad_err2         208
ra                      1
dec                     1
koi_kepmag              1
dtype: int64

In [ ]:
df.describe()

,kepid,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
count,6.314000e+03,5786.000000,6313.000000,6313.000000,6313.000000,6313.000000,6313.000000,6146.000000,6146.000000,6313.000000,...,6092.000000,6184.000000,6106.000000,6106.000000,6184.000000,6106.000000,6106.000000,6313.000000,6313.000000,6313.000000
mean,7.549533e+06,0.592698,0.168700,0.195311,0.217646,0.119119,62.025017,0.001059,-0.001059,160.541505,...,-153.314018,4.349985,0.109702,-0.134184,1.526075,0.309818,-0.315762,291.988412,43.629045,14.385989
std,2.687113e+06,0.471721,5.858564,0.396472,0.412678,0.323954,1638.666068,0.005945,0.005945,55.615503,...,68.271085,0.383414,0.120818,0.077147,5.238020,0.924564,1.762286,4.774406,3.627950,1.338025
min,7.574500e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.241843,0.000000,-0.173000,120.565925,...,-1733.000000,0.114000,0.000000,-0.856000,0.116000,0.000000,-103.825000,279.852720,36.577381,6.974000
25%,5.468029e+06,0.000000,0.000000,0.000000,0.000000,0.000000,2.992663,0.000006,-0.000150,133.061470,...,-191.000000,4.274000,0.041000,-0.192000,0.824000,0.110000,-0.192750,288.584050,40.659191,13.592000
50%,7.660227e+06,0.964000,0.000000,0.000000,0.000000,0.000000,8.752097,0.000031,-0.000031,137.447816,...,-152.000000,4.449000,0.066000,-0.120000,0.982000,0.218000,-0.104000,292.219060,43.304451,14.659000
75%,9.820984e+06,1.000000,0.000000,0.000000,0.000000,0.000000,27.881315,0.000150,-0.000006,170.453117,...,-101.750000,4.548000,0.137000,-0.084000,1.243250,0.326000,-0.066000,295.788120,46.610592,15.368000
max,1.293514e+07,1.000000,465.000000,1.000000,1.000000,1.000000,129995.778400,0.173000,0.000000,907.044710,...,0.000000,5.283000,1.472000,0.000000,180.013000,33.091000,0.000000,301.720760,52.336010,19.319000

We currently have three classes, but we could simplify it to two as we are creating a machine learning model that will give the probability of it being a candidate or not.

In [ ]:
df['koi_disposition'].value_counts()

koi_disposition
CONFIRMED         2692
FALSE POSITIVE    2612
CANDIDATE         1009
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 49 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   kepid              9564 non-null   int64
 1   kepoi_name         9564 non-null   object
 2   kepler_name        2747 non-null   object
 3   koi_disposition    9564 non-null   object
 4   koi_pdisposition   9564 non-null   object
 5   koi_score          8054 non-null   float64
 6   koi_fpflag_nt      9564 non-null   int64
 7   koi_fpflag_ss      9564 non-null   int64
 8   koi_fpflag_co      9564 non-null   int64
 9   koi_fpflag_ec      9564 non-null   int64
 10  koi_period         9564 non-null   float64
 11  koi_period_err1    9110 non-null   float64
 12  koi_period_err2    9110 non-null   float64
 13  koi_time0bk        9564 non-null   float64
 14  koi_time0bk_err1   9110 non-null   float64
 15  koi_time0bk_err2   9110 non-null   float64
 16  koi_impact         9201 non-null   float64
 17  koi_impact_err1    9110 non-null   float64
 18  koi_impact_err2    9110 non-null   float64
 19  koi_duration       9564 non-null   float64
 20  koi_duration_err1  9110 non-null   float64
 21  koi_duration_err2  9110 non-null   float64
 22  koi_depth          9201 non-null   float64
 23  koi_depth_err1     9110 non-null   float64
 24  koi_depth_err2     9110 non-null   float64
 25  koi_prad           9201 non-null   float64
 26  koi_prad_err1      9201 non-null   float64
 27  koi_prad_err2      9201 non-null   float64
 28  koi_teq            9201 non-null   float64
 29  koi_teq_err1       0 non-null      float64
 30  koi_teq_err2       0 non-null      float64
 31  koi_insol          9243 non-null   float64
 32  koi_insol_err1     9243 non-null   float64
 33  koi_insol_err2     9243 non-null   float64
 34  koi_model_snr      9201 non-null   float64
 35  koi_tce_plnt_num   9218 non-null   float64
 36  koi_tce_delivname  9218 non-null   object
 37  koi_steff          9201 non-null   float64
 38  koi_steff_err1     9096 non-null   float64
 39  koi_steff_err2     9081 non-null   float64
 40  koi_slogg          9201 non-null   float64
 41  koi_slogg_err1     9096 non-null   float64
 42  koi_slogg_err2     9096 non-null   float64
 43  koi_srad           9201 non-null   float64
 44  koi_srad_err1      9096 non-null   float64
 45  koi_srad_err2      9096 non-null   float64
 46  ra                 9564 non-null   float64
 47  dec                9564 non-null   float64
 48  koi_kepmag         9563 non-null   float64
dtypes: float64(39), int64(5), object(5)
memory usage: 3.6+ MB

In [ ]:
df.drop(['koi_teq_err1', 'koi_teq_err2'], axis=1, inplace=True)

We drop the kepler name as it is not needed for the classification model, and also allows us to eliminate the null values.

In [ ]:
df2 = df.drop(['kepler_name'], axis=1)

Now we can drop all the null values.

In [ ]:
df2.dropna(inplace=True)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5652 entries, 0 to 6311
Data columns (total 46 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   kepid              5652 non-null   int64
 1   kepoi_name         5652 non-null   object
 2   koi_disposition    5652 non-null   object
 3   koi_pdisposition   5652 non-null   object
 4   koi_score          5652 non-null   float64
 5   koi_fpflag_nt      5652 non-null   float64
 6   koi_fpflag_ss      5652 non-null   float64
 7   koi_fpflag_co      5652 non-null   float64
 8   koi_fpflag_ec      5652 non-null   float64
 9   koi_period         5652 non-null   float64
 10  koi_period_err1    5652 non-null   float64
 11  koi_period_err2    5652 non-null   float64
 12  koi_time0bk        5652 non-null   float64
 13  koi_time0bk_err1   5652 non-null   float64
 14  koi_time0bk_err2   5652 non-null   float64
 15  koi_impact         5652 non-null   float64
 16  koi_impact_err1    5652 non-null   float64
 17  koi_impact_err2    5652 non-null   float64
 18  koi_duration       5652 non-null   float64
 19  koi_duration_err1  5652 non-null   float64
 20  koi_duration_err2  5652 non-null   float64
 21  koi_depth          5652 non-null   float64
 22  koi_depth_err1     5652 non-null   float64
 23  koi_depth_err2     5652 non-null   float64
 24  koi_prad           5652 non-null   float64
 25  koi_prad_err1      5652 non-null   float64
 26  koi_prad_err2      5652 non-null   float64
 27  koi_teq            5652 non-null   float64
 28  koi_insol          5652 non-null   float64
 29  koi_insol_err1     5652 non-null   float64
 30  koi_insol_err2     5652 non-null   float64
 31  koi_model_snr      5652 non-null   float64
 32  koi_tce_plnt_num   5652 non-null   float64
 33  koi_tce_delivname  5652 non-null   object
 34  koi_steff          5652 non-null   float64
 35  koi_steff_err1     5652 non-null   float64
 36  koi_steff_err2     5652 non-null   float64
 37  koi_slogg          5652 non-null   float64
 38  koi_slogg_err1     5652 non-null   float64
 39  koi_slogg_err2     5652 non-null   float64
 40  koi_srad           5652 non-null   float64
 41  koi_srad_err1      5652 non-null   float64
 42  koi_srad_err2      5652 non-null   float64
 43  ra                 5652 non-null   float64
 44  dec                5652 non-null   float64
 45  koi_kepmag         5652 non-null   float64
dtypes: float64(41), int64(1), object(4)
memory usage: 2.0+ MB

The data is clean.

In [ ]:
df2.isnull().sum()

kepid                0
kepoi_name           0
koi_disposition      0
koi_pdisposition     0
koi_score            0
koi_fpflag_nt        0
koi_fpflag_ss        0
koi_fpflag_co        0
koi_fpflag_ec        0
koi_period           0
koi_period_err1      0
koi_period_err2      0
koi_time0bk          0
koi_time0bk_err1     0
koi_time0bk_err2     0
koi_impact           0
koi_impact_err1      0
koi_impact_err2      0
koi_duration         0
koi_duration_err1    0
koi_duration_err2    0
koi_depth            0
koi_depth_err1       0
koi_depth_err2       0
koi_prad             0
koi_prad_err1        0
koi_prad_err2        0
koi_teq              0
koi_insol            0
koi_insol_err1       0
koi_insol_err2       0
koi_model_snr        0
koi_tce_plnt_num     0
koi_tce_delivname    0
koi_steff            0
koi_steff_err1       0
koi_steff_err2       0
koi_slogg            0
koi_slogg_err1       0
koi_slogg_err2       0
koi_srad             0
koi_srad_err1        0
koi_srad_err2        0
ra                   0
dec                  0
koi_kepmag           0
dtype: int64

In [ ]:
df2.to_csv('cleaned_exoplanet.csv', index=False)

In [ ]:
df2['koi_disposition'].value_counts()

koi_disposition
FALSE POSITIVE    3735
CONFIRMED         2712
CANDIDATE         1356
Name: count, dtype: int64

In [ ]:
df2['koi_disposition'] = df2['koi_disposition'].replace(['CONFIRMED', 'CANDIDATE'], 1)
df2['koi_disposition'] = df2['koi_disposition'].replace('FALSE POSITIVE', 0)

In [ ]:
df2['koi_disposition'].value_counts()

koi_disposition
1    4068
0    3735
Name: count, dtype: int64

In [ ]:
df2.to_csv('cleaned_exoplanet_v2.csv', index=False)

In [ ]:
df = pd.read_csv('/content/cleaned_exoplanet_v2.csv')

In [ ]:
df.describe()

,kepid,koi_disposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
count,7.803000e+03,7803.000000,7803.000000,7803.000000,7803.000000,7803.000000,7803.000000,7803.000000,7.803000e+03,7.803000e+03,...,7803.000000,7803.000000,7803.000000,7803.000000,7803.000000,7803.000000,7803.000000,7803.000000,7803.000000,7803.000000
mean,7.709742e+06,0.521338,0.491614,0.159041,0.265667,0.217993,0.133538,37.314267,9.484169e-04,-9.484169e-04,...,-159.049084,4.320219,0.120392,-0.131442,1.678491,0.317228,-0.371328,292.073715,43.836122,14.309852
std,2.651124e+06,0.499576,0.477082,5.271453,0.441716,0.412909,0.340177,86.826061,5.021474e-03,5.021474e-03,...,74.361117,0.420923,0.132785,0.067304,5.871606,0.851312,1.881014,4.787246,3.599892,1.335016
min,7.574500e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.259820,1.100000e-08,-1.340000e-01,...,-1762.000000,0.047000,0.000000,-0.777000,0.109000,0.000000,-103.825000,279.856080,36.577381,6.966000
25%,5.601923e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.455472,4.225000e-06,-1.340000e-04,...,-195.000000,4.228000,0.044000,-0.188000,0.826000,0.120000,-0.234000,288.681730,40.814960,13.519000
50%,7.939330e+06,1.000000,0.475000,0.000000,0.000000,0.000000,0.000000,7.698431,2.450000e-05,-2.450000e-05,...,-158.000000,4.442000,0.071000,-0.121000,0.993000,0.232000,-0.111000,292.294590,43.718182,14.582000
75%,9.886361e+06,1.000000,0.999000,0.000000,1.000000,0.000000,0.000000,24.089219,1.340000e-04,-4.225000e-06,...,-105.500000,4.545000,0.149000,-0.087000,1.319500,0.333000,-0.069000,295.895305,46.734850,15.333500
max,1.293514e+07,1.000000,1.000000,465.000000,1.000000,1.000000,1.000000,1071.232624,1.340000e-01,-1.100000e-08,...,0.000000,5.364000,1.472000,0.000000,180.013000,33.091000,0.000000,301.720760,52.336010,19.065000

In [ ]:
df2 = pd.read_csv('/content/TESS.csv')

In [ ]:
df2.head()

,tfopwg_disp,rastr,ra,decstr,dec,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_trandurh,...,st_tefferr2,st_tefflim,st_logg,st_loggerr1,st_loggerr2,st_logglim,st_rad,st_raderr1,st_raderr2,st_radlim
0,FP,07h29m25.85s,112.357708,-12d41m45.46s,-12.695960,2.171348,0.000264,-0.000264,0.0,2.01722,...,-264.7,0.0,4.19,0.07,-0.07,0.0,2.16986,0.072573,-0.072573,0.0
1,PC,08h10m19.31s,122.580465,-05d30m49.87s,-5.513852,1.931646,0.000005,-0.000005,0.0,3.16600,...,-126.4,0.0,4.03,0.09,-0.09,0.0,2.01000,0.090000,-0.090000,0.0
2,FP,06h58m54.47s,104.726966,-10d34m49.64s,-10.580455,1.867557,0.000003,-0.000003,0.0,1.40800,...,-124.0,0.0,NaN,NaN,NaN,0.0,5.73000,NaN,NaN,0.0
3,FP,07h22m14.39s,110.559945,-25d12m25.26s,-25.207017,2.743230,0.001080,-0.001080,0.0,3.16700,...,-567.0,0.0,4.15,1.64,-1.64,0.0,NaN,NaN,NaN,0.0
4,FP,08h08m42.77s,122.178195,-48d48m10.12s,-48.802811,3.573014,0.000013,-0.000013,0.0,3.37000,...,-171.1,0.0,4.14,0.07,-0.07,0.0,2.15000,0.060000,-0.060000,0.0

In [ ]:
display(df['koi_disposition'].value_counts())

koi_disposition
1    4068
0    3735
Name: count, dtype: int64

In [ ]:
df2['tfopwg_disp'] = df2['tfopwg_disp'].replace(['CP', 'KP', 'PC', 'APC'], 1)
df2['tfopwg_disp'] = df2['tfopwg_disp'].replace(['FP', 'FA'], 0)
display(df2['tfopwg_disp'].value_counts())

/tmp/ipython-input-3548447221.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['tfopwg_disp'] = df2['tfopwg_disp'].replace(['FP', 'FA'], 0)

tfopwg_disp
1    3474
0     939
Name: count, dtype: int64

In [ ]:
df_kepler = df[['koi_disposition', 'koi_period', 'koi_duration', 'koi_depth', 'koi_prad', 'koi_insol', 'koi_teq', 'koi_steff', 'koi_slogg', 'koi_srad', 'ra', 'dec']]
df_tess = df2[['tfopwg_disp', 'pl_orbper', 'pl_trandurh', 'pl_trandep', 'pl_rade', 'pl_insol', 'pl_eqt', 'st_teff', 'st_logg', 'st_rad', 'ra', 'dec']]

In [ ]:
column_mapping = {
    'tfopwg_disp': 'koi_disposition',
    'pl_orbper': 'koi_period',
    'pl_trandurh': 'koi_duration',
    'pl_trandep': 'koi_depth',
    'pl_rade': 'koi_prad',
    'pl_insol': 'koi_insol',
    'pl_eqt': 'koi_teq',
    'st_teff': 'koi_steff',
    'st_logg': 'koi_slogg',
    'st_rad': 'koi_srad',
    'ra': 'ra',
    'dec': 'dec'
}
df_tess.rename(columns=column_mapping, inplace=True)
display(df_tess.head())

/tmp/ipython-input-4246934478.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tess.rename(columns=column_mapping, inplace=True)

,koi_disposition,koi_period,koi_duration,koi_depth,koi_prad,koi_insol,koi_teq,koi_steff,koi_slogg,koi_srad,ra,dec
0,0,2.171348,2.01722,656.886099,5.818163,22601.94858,3127.204052,10249.0,4.19,2.16986,112.357708,-12.695960
1,1,1.931646,3.16600,1286.000000,11.215400,44464.50000,4045.000000,7070.0,4.03,2.01000,122.580465,-5.513852
2,0,1.867557,1.40800,1500.000000,23.752900,2860.61000,2037.000000,8924.0,NaN,5.73000,104.726966,-10.580455
3,0,2.743230,3.16700,383.410000,NaN,1177.36000,1631.000000,5388.5,4.15,NaN,110.559945,-25.207017
4,0,3.573014,3.37000,755.000000,11.311300,54679.30000,4260.000000,9219.0,4.14,2.15000,122.178195,-48.802811

In [ ]:
combined_df = pd.concat([df_kepler, df_tess], ignore_index=True)
display(combined_df.head())
display(combined_df.shape)

,koi_disposition,koi_period,koi_duration,koi_depth,koi_prad,koi_insol,koi_teq,koi_steff,koi_slogg,koi_srad,ra,dec
0,1,9.488036,2.95750,616.0,2.26,93.59,793.0,5455.0,4.467,0.927,291.93423,48.141651
1,1,54.418383,4.50700,875.0,2.83,9.11,443.0,5455.0,4.467,0.927,291.93423,48.141651
2,1,19.899140,1.78220,10800.0,14.60,39.30,638.0,5853.0,4.544,0.868,297.00482,48.134129
3,0,1.736952,2.40641,8080.0,33.46,891.96,1395.0,5805.0,4.564,0.791,285.53461,48.285210
4,1,2.525592,1.65450,603.0,2.75,926.16,1406.0,6031.0,4.438,1.046,288.75488,48.226200

(12216, 12)

In [ ]:
# Replace this dictionary with your desired column name mapping
new_column_names = {
    'koi_disposition': 'disposition',
    'koi_period': 'orbital_period_days',
    'koi_duration': 'transit_duration_hours',
    'koi_depth': 'transit_depth_ppm',
    'koi_prad': 'planetary_radius_earth_radii',
    'koi_insol': 'insolation_flux_earth_flux',
    'koi_teq': 'equilibrium_temperature_k',
    'koi_steff': 'stellar_effective_temperature_k',
    'koi_slogg': 'stellar_surface_gravity_log10_cm_s2',
    'koi_srad': 'stellar_radius_solar_radii',
    'ra': 'right_ascension_decimal_degrees',
    'dec': 'declination_decimal_degrees'
}

combined_df.rename(columns=new_column_names, inplace=True)
display(combined_df.head())

,disposition,orbital_period_days,transit_duration_hours,transit_depth_ppm,planetary_radius_earth_radii,insolation_flux_earth_flux,equilibrium_temperature_k,stellar_effective_temperature_k,stellar_surface_gravity_log10_cm_s2,stellar_radius_solar_radii,right_ascension_decimal_degrees,declination_decimal_degrees
0,1,9.488036,2.95750,616.0,2.26,93.59,793.0,5455.0,4.467,0.927,291.93423,48.141651
1,1,54.418383,4.50700,875.0,2.83,9.11,443.0,5455.0,4.467,0.927,291.93423,48.141651
2,1,19.899140,1.78220,10800.0,14.60,39.30,638.0,5853.0,4.544,0.868,297.00482,48.134129
3,0,1.736952,2.40641,8080.0,33.46,891.96,1395.0,5805.0,4.564,0.791,285.53461,48.285210
4,1,2.525592,1.65450,603.0,2.75,926.16,1406.0,6031.0,4.438,1.046,288.75488,48.226200

In [ ]:
combined_df.shape

(12216, 12)

In [ ]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12216 entries, 0 to 12215
Data columns (total 12 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   disposition                          12216 non-null  int64
 1   orbital_period_days                  12154 non-null  float64
 2   transit_duration_hours               12215 non-null  float64
 3   transit_depth_ppm                    12215 non-null  float64
 4   planetary_radius_earth_radii         11822 non-null  float64
 5   insolation_flux_earth_flux           12093 non-null  float64
 6   equilibrium_temperature_k            12001 non-null  float64
 7   stellar_effective_temperature_k      12105 non-null  float64
 8   stellar_surface_gravity_log10_cm_s2  11577 non-null  float64
 9   stellar_radius_solar_radii           11822 non-null  float64
 10  right_ascension_decimal_degrees      12215 non-null  float64
 11  declination_decimal_degrees          12215 non-null  float64
dtypes: float64(11), int64(1)
memory usage: 1.1 MB

In [ ]:
combined_df.dropna(inplace=True)

In [ ]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11436 entries, 0 to 12213
Data columns (total 12 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   disposition                          11436 non-null  int64
 1   orbital_period_days                  11436 non-null  float64
 2   transit_duration_hours               11436 non-null  float64
 3   transit_depth_ppm                    11436 non-null  float64
 4   planetary_radius_earth_radii         11436 non-null  float64
 5   insolation_flux_earth_flux           11436 non-null  float64
 6   equilibrium_temperature_k            11436 non-null  float64
 7   stellar_effective_temperature_k      11436 non-null  float64
 8   stellar_surface_gravity_log10_cm_s2  11436 non-null  float64
 9   stellar_radius_solar_radii           11436 non-null  float64
 10  right_ascension_decimal_degrees      11436 non-null  float64
 11  declination_decimal_degrees          11436 non-null  float64
dtypes: float64(11), int64(1)
memory usage: 1.1 MB

In [ ]:
combined_df.to_csv('final_dataset_exoplanet_v2.csv', index=True)